-- Joy's Pizza menu. Run in Supabase -> SQL Editor. Replaces the whole menu.
begin;
delete from menu_items;
insert into menu_items ("Id","Name","Description","Price","Category","ImageUrl","Tags","IsSpecial","IsAvailable","Sizes","SortOrder","CreatedAt","UpdatedAt") values
('pz-cheese','Cheese Pizza','Classic cheese pizza with tomato sauce and mozzarella. Deal: Buy 2 Large, get 1 Medium FREE!',12.99,'Pizza','','{"Deal"}',true,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 12.99}, {"Label": "Large 16\" · 16 slices", "Price": 14.99}]'::jsonb,1,now(),now()),
('pz-pepperoni','Pepperoni Pizza','Tomato sauce, mozzarella and pepperoni.',14.99,'Pizza','','{"Best seller"}',true,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,2,now(),now()),
('pz-sausage','Sausage Pizza','Tomato sauce, mozzarella and Italian sausage.',14.99,'Pizza','','{}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,3,now(),now()),
('pz-bacon','Bacon Pizza','Tomato sauce, mozzarella and crispy bacon.',14.99,'Pizza','','{}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,4,now(),now()),
('pz-chicken-buffalo-bbq','Buffalo / BBQ Chicken Pizza','Chicken with your choice of Buffalo or BBQ sauce (add your choice in the order notes).',16.99,'Pizza','','{"Spicy"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 16.99}, {"Label": "Large 16\" · 16 slices", "Price": 18.99}]'::jsonb,5,now(),now()),
('pz-meat-lovers','Meat Lovers Pizza','Ground beef, ham, pepperoni and sausage.',16.99,'Pizza','','{}',true,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 16.99}, {"Label": "Large 16\" · 16 slices", "Price": 18.99}]'::jsonb,6,now(),now()),
('pz-supreme','Special / Supreme Pizza','Onion, green pepper, olives, mushrooms, ham, sausage and pepperoni.',16.99,'Pizza','','{}',true,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 16.99}, {"Label": "Large 16\" · 16 slices", "Price": 18.99}]'::jsonb,7,now(),now()),
('pz-hawaiian','Hawaiian Pizza','Ham and pineapple.',16.99,'Pizza','','{}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 16.99}, {"Label": "Large 16\" · 16 slices", "Price": 18.99}]'::jsonb,8,now(),now()),
('pz-chicken-caesar','Chicken Caesar Pizza','Chicken, lettuce, croutons and parmesan cheese.',16.99,'Pizza','','{}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 16.99}, {"Label": "Large 16\" · 16 slices", "Price": 18.99}]'::jsonb,9,now(),now()),
('pz-greek','Greek Pizza','Spinach, tomato, garlic, kalamata olives and feta cheese.',16.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 16.99}, {"Label": "Large 16\" · 16 slices", "Price": 18.99}]'::jsonb,10,now(),now()),
('pz-veggie-lovers','Veggie Lovers Pizza','Spinach, onion, green pepper, broccoli, mushrooms, olives and cauliflower.',16.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 16.99}, {"Label": "Large 16\" · 16 slices", "Price": 18.99}]'::jsonb,11,now(),now()),
('pz-tomato','Tomato Pizza','Fresh tomato pizza.',14.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,12,now(),now()),
('pz-white','White Pizza','Ricotta and mozzarella, no tomato sauce.',14.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,13,now(),now()),
('pz-grandma','Grandma Pizza','Thin square pie with tomato sauce, mozzarella and garlic.',14.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,14,now(),now()),
('pz-sicilian','Sicilian Pizza','Thick square pie with tomato sauce and mozzarella.',14.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,15,now(),now()),
('pz-margherita','Margherita Pizza','Tomato, fresh mozzarella and basil.',14.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,16,now(),now()),
('pz-jalapeno','Jalapeño Pizza','Mozzarella and jalapeño peppers.',14.99,'Pizza','','{"Spicy","Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,17,now(),now()),
('pz-garlic','Garlic Pizza','Mozzarella, garlic and olive oil.',14.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,18,now(),now()),
('pz-mushroom','Mushroom Pizza','Tomato sauce, mozzarella and mushrooms.',14.99,'Pizza','','{"Vegetarian"}',false,true,'[{"Label": "Medium 14\" · 8 slices", "Price": 14.99}, {"Label": "Large 16\" · 16 slices", "Price": 16.99}]'::jsonb,19,now(),now()),
('pa-alfredo','Fettuccine Alfredo','Creamy Alfredo sauce with parmesan.',9.99,'Pasta','','{"Vegetarian"}',false,true,'[]'::jsonb,1,now(),now()),
('pa-vodka','Penne alla Vodka','Penne in a creamy tomato-vodka sauce.',9.99,'Pasta','','{"Vegetarian"}',false,true,'[]'::jsonb,2,now(),now()),
('hr-chicken-parm','Chicken Parmesan Hero','Breaded chicken, marinara and melted mozzarella on a hero roll.',8.99,'Burgers','','{}',false,true,'[]'::jsonb,1,now(),now()),
('hr-chicken-cutlet','Chicken Cutlet Hero','Crispy chicken cutlet on a hero roll.',8.99,'Burgers','','{}',false,true,'[]'::jsonb,2,now(),now()),
('hr-meatball','Meatball Hero','Meatballs, marinara and mozzarella on a hero roll.',8.99,'Burgers','','{}',false,true,'[]'::jsonb,3,now(),now()),
('bg-cheese','Cheeseburger','Beef burger with cheese.',5.99,'Burgers','','{}',false,true,'[]'::jsonb,4,now(),now()),
('bg-chicken','Chicken Burger','Chicken burger.',5.99,'Burgers','','{}',false,true,'[]'::jsonb,5,now(),now()),
('sl-garden','Garden Salad','Lettuce, onion, green pepper and tomato with Italian dressing.',9.99,'Salads','','{"Vegetarian"}',false,true,'[{"Label": "Regular", "Price": 9.99}, {"Label": "With chicken (+$3)", "Price": 12.99}]'::jsonb,1,now(),now()),
('sl-greek','Greek Salad','Lettuce, onion, green pepper, kalamata olives and feta cheese with Italian dressing.',9.99,'Salads','','{"Vegetarian"}',false,true,'[{"Label": "Regular", "Price": 9.99}, {"Label": "With chicken (+$3)", "Price": 12.99}]'::jsonb,2,now(),now()),
('sl-caesar','Caesar Salad','Lettuce, croutons and parmesan cheese with Caesar dressing.',9.99,'Salads','','{}',false,true,'[{"Label": "Regular", "Price": 9.99}, {"Label": "With chicken (+$3)", "Price": 12.99}]'::jsonb,3,now(),now()),
('ap-fries','French Fries','Crispy golden fries.',4.99,'Appetizers','','{"Vegetarian"}',false,true,'[]'::jsonb,1,now(),now()),
('ap-mozz-sticks','Mozzarella Sticks (6 pcs)','Six breaded mozzarella sticks with marinara.',7.99,'Appetizers','','{"Vegetarian"}',false,true,'[]'::jsonb,2,now(),now()),
('ap-nuggets','Chicken Nuggets (10 pcs)','Ten crispy chicken nuggets.',9.99,'Appetizers','','{}',false,true,'[]'::jsonb,3,now(),now()),
('ap-poppers','Jalapeño Poppers (6 pcs)','Six cheese-filled jalapeño poppers.',7.99,'Appetizers','','{"Spicy","Vegetarian"}',false,true,'[]'::jsonb,4,now(),now()),
('ap-plantains','Sweet Plantains (6 pcs)','Six fried sweet plantains.',7.99,'Appetizers','','{"Vegetarian"}',false,true,'[]'::jsonb,5,now(),now()),
('ap-wings','Jumbo Wings','Choose Buffalo, BBQ or Mango Habanero, with Blue Cheese or Ranch (add your choice in the order notes).',8.99,'Appetizers','','{"Spicy"}',true,true,'[{"Label": "6 pcs", "Price": 8.99}, {"Label": "10 pcs", "Price": 15.99}, {"Label": "15 pcs", "Price": 19.99}]'::jsonb,6,now(),now()),
('dr-water','Water','Bottled water.',1.25,'Drinks','','{}',false,true,'[]'::jsonb,1,now(),now()),
('dr-can-soda','Can Soda','Ask for your flavor in the order notes.',1.99,'Drinks','','{}',false,true,'[]'::jsonb,2,now(),now()),
('dr-bottle-soda','Bottle Soda','Ask for your flavor in the order notes.',3.50,'Drinks','','{}',false,true,'[]'::jsonb,3,now(),now()),
('dr-2l-soda','2 Liter Soda','Ask for your flavor in the order notes.',4.99,'Drinks','','{}',false,true,'[]'::jsonb,4,now(),now()),
('ds-cheesecake','Cheesecake','Creamy New York cheesecake.',5.99,'Desserts','','{"Vegetarian"}',false,true,'[]'::jsonb,1,now(),now()),
('ds-carrot-cake','Carrot Cake','Carrot cake with cream cheese frosting.',5.99,'Desserts','','{"Vegetarian"}',false,true,'[]'::jsonb,2,now(),now()),
('ds-chocolate-cake','Chocolate Cake','Rich chocolate layer cake.',5.99,'Desserts','','{"Vegetarian"}',false,true,'[]'::jsonb,3,now(),now());
commit;
